import 'package:cloud_firestore/cloud_firestore.dart';

Future<void> seedFBLAEvents() async {
  final firestore = FirebaseFirestore.instance;

  final existing = await firestore.collection('events').limit(1).get();
  if (existing.docs.isNotEmpty) {
    print('Events already seeded. Skipping...');
    return;
  }

  final events = [
    {
      'title': 'FBLA Regional Competition',
      'description': 'Regional FBLA competitive events including Mobile App Development, Public Speaking, and Accounting.',
      'date': Timestamp.fromDate(DateTime(2026, 2, 10, 8, 0)),
      'endDate': Timestamp.fromDate(DateTime(2026, 2, 10, 17, 0)),
      'location': 'Wake Technical Community College',
      'eventType': 'competition',
      'registrationDeadline': Timestamp.fromDate(DateTime(2026, 2, 1)),
      'maxParticipants': 50,
      'registeredUsers': [],
      'organizer': 'NC FBLA',
      'isVirtual': false,
      'createdBy': 'system',
      'createdAt': Timestamp.now(),
    },
    {
      'title': 'Mobile App Development Practice Session',
      'description': 'Practice presentations and feedback for students preparing for the Mobile Application Development competition.',
      'date': Timestamp.fromDate(DateTime(2026, 1, 15, 15, 30)),
      'endDate': Timestamp.fromDate(DateTime(2026, 1, 15, 17, 30)),
      'location': 'School Computer Lab',
      'eventType': 'competition',
      'registrationDeadline': Timestamp.fromDate(DateTime(2026, 1, 14)),
      'maxParticipants': 20,
      'registeredUsers': [],
      'organizer': 'FBLA Advisor',
      'isVirtual': false,
      'createdBy': 'system',
      'createdAt': Timestamp.now(),
    },
    {
      'title': 'Weekly FBLA Chapter Meeting',
      'description': 'Discuss upcoming competitions, leadership opportunities, and chapter updates.',
      'date': Timestamp.fromDate(DateTime(2026, 1, 8, 15, 0)),
      'endDate': Timestamp.fromDate(DateTime(2026, 1, 8, 16, 0)),
      'location': 'Room B204',
      'eventType': 'meeting',
      'registrationDeadline': Timestamp.fromDate(DateTime(2026, 1, 7)),
      'maxParticipants': 40,
      'registeredUsers': [],
      'organizer': 'Chapter President',
      'isVirtual': false,
      'createdBy': 'system',
      'createdAt': Timestamp.now(),
    },
    {
      'title': 'Officer Leadership Meeting',
      'description': 'Planning meeting for FBLA officers to organize events and activities.',
      'date': Timestamp.fromDate(DateTime(2026, 1, 22, 15, 15)),
      'endDate': Timestamp.fromDate(DateTime(2026, 1, 22, 16, 30)),
      'location': 'Media Center',
      'eventType': 'meeting',
      'registrationDeadline': Timestamp.fromDate(DateTime(2026, 1, 21)),
      'maxParticipants': 10,
      'registeredUsers': [],
      'organizer': 'Chapter President',
      'isVirtual': false,
      'createdBy': 'system',
      'createdAt': Timestamp.now(),
    },
    {
      'title': 'Resume Building Workshop',
      'description': 'Learn how to build professional resumes and prepare for internships.',
      'date': Timestamp.fromDate(DateTime(2026, 2, 5, 15, 30)),
      'endDate': Timestamp.fromDate(DateTime(2026, 2, 5, 17, 0)),
      'location': 'Career Center',
      'eventType': 'workshop',
      'registrationDeadline': Timestamp.fromDate(DateTime(2026, 2, 4)),
      'maxParticipants': 25,
      'registeredUsers': [],
      'organizer': 'Career Counselor',
      'isVirtual': false,
      'createdBy': 'system',
      'createdAt': Timestamp.now(),
    },
    {
      'title': 'Public Speaking Bootcamp',
      'description': 'Improve presentation and speaking skills for FBLA competitive events.',
      'date': Timestamp.fromDate(DateTime(2026, 2, 18, 15, 30)),
      'endDate': Timestamp.fromDate(DateTime(2026, 2, 18, 17, 30)),
      'location': 'Auditorium',
      'eventType': 'workshop',
      'registrationDeadline': Timestamp.fromDate(DateTime(2026, 2, 17)),
      'maxParticipants': 30,
      'registeredUsers': [],
      'organizer': 'Speech Teacher',
      'isVirtual': false,
      'createdBy': 'system',
      'createdAt': Timestamp.now(),
    },
    {
      'title': 'FBLA Game Night',
      'description': 'Networking and team building with games and snacks.',
      'date': Timestamp.fromDate(DateTime(2026, 1, 30, 16, 0)),
      'endDate': Timestamp.fromDate(DateTime(2026, 1, 30, 19, 0)),
      'location': 'Student Lounge',
      'eventType': 'social',
      'registrationDeadline': Timestamp.fromDate(DateTime(2026, 1, 29)),
      'maxParticipants': 30,
      'registeredUsers': [],
      'organizer': 'Social Committee',
      'isVirtual': false,
      'createdBy': 'system',
      'createdAt': Timestamp.now(),
    },
    {
      'title': 'Community Food Drive',
      'description': 'Help organize and distribute food donations for local families.',
      'date': Timestamp.fromDate(DateTime(2026, 2, 12, 14, 30)),
      'endDate': Timestamp.fromDate(DateTime(2026, 2, 12, 17, 30)),
      'location': 'School Entrance',
      'eventType': 'service',
      'registrationDeadline': Timestamp.fromDate(DateTime(2026, 2, 11)),
      'maxParticipants': 50,
      'registeredUsers': [],
      'organizer': 'Community Service VP',
      'isVirtual': false,
      'createdBy': 'system',
      'createdAt': Timestamp.now(),
    },
    {
      'title': 'Volunteer at Local Business Fair',
      'description': 'Assist local businesses with event setup and registration.',
      'date': Timestamp.fromDate(DateTime(2026, 3, 5, 10, 0)),
      'endDate': Timestamp.fromDate(DateTime(2026, 3, 5, 15, 0)),
      'location': 'Downtown Civic Center',
      'eventType': 'service',
      'registrationDeadline': Timestamp.fromDate(DateTime(2026, 3, 4)),
      'maxParticipants': 15,
      'registeredUsers': [],
      'organizer': 'Community Service VP',
      'isVirtual': false,
      'createdBy': 'system',
      'createdAt': Timestamp.now(),
    },
    {
      'title': 'Krispy Kreme Fundraiser',
      'description': 'Sell donuts to raise funds for state conference travel.',
      'date': Timestamp.fromDate(DateTime(2026, 1, 28, 15, 0)),
      'endDate': Timestamp.fromDate(DateTime(2026, 1, 28, 18, 0)),
      'location': 'School Parking Lot',
      'eventType': 'fundraiser',
      'registrationDeadline': Timestamp.fromDate(DateTime(2026, 1, 27)),
      'maxParticipants': 20,
      'registeredUsers': [],
      'organizer': 'Fundraising Chair',
      'isVirtual': false,
      'createdBy': 'system',
      'createdAt': Timestamp.now(),
    },
    {
      'title': 'FBLA T-Shirt Sale',
      'description': 'Sell FBLA merchandise to support chapter activities.',
      'date': Timestamp.fromDate(DateTime(2026, 2, 20, 15, 0)),
      'endDate': Timestamp.fromDate(DateTime(2026, 2, 20, 17, 0)),
      'location': 'School Cafeteria',
      'eventType': 'fundraiser',
      'registrationDeadline': Timestamp.fromDate(DateTime(2026, 2, 19)),
      'maxParticipants': 15,
      'registeredUsers': [],
      'organizer': 'Fundraising Chair',
      'isVirtual': false,
      'createdBy': 'system',
      'createdAt': Timestamp.now(),
    },
    {
      'title': 'State Leadership Conference 2026',
      'description': 'Annual FBLA State Leadership Conference – compete, attend workshops, and network.',
      'date': Timestamp.fromDate(DateTime(2026, 3, 20, 9, 0)),
      'endDate': Timestamp.fromDate(DateTime(2026, 3, 22, 17, 0)),
      'location': 'Raleigh Convention Center, NC',
      'eventType': 'competition',
      'registrationDeadline': Timestamp.fromDate(DateTime(2026, 3, 1)),
      'maxParticipants': 500,
      'registeredUsers': [],
      'organizer': 'NC FBLA',
      'isVirtual': false,
      'createdBy': 'system',
      'createdAt': Timestamp.now(),
    },
    {
      'title': 'Public Speaking Workshop',
      'description': 'Learn tips and tricks for FBLA presentation events from state winners.',
      'date': Timestamp.fromDate(DateTime(2026, 2, 25, 15, 0)),
      'endDate': Timestamp.fromDate(DateTime(2026, 2, 25, 17, 0)),
      'location': 'Online (Zoom)',
      'eventType': 'workshop',
      'registrationDeadline': Timestamp.fromDate(DateTime(2026, 2, 24)),
      'maxParticipants': 100,
      'registeredUsers': [],
      'organizer': 'State Officer Team',
      'isVirtual': true,
      'meetingLink': 'https://zoom.us/j/123456789',
      'createdBy': 'system',
      'createdAt': Timestamp.now(),
    },
    {
      'title': 'FBLA Bonfire Social',
      'description': 'End‑of‑semester bonfire – food, games, and fellowship.',
      'date': Timestamp.fromDate(DateTime(2026, 5, 15, 19, 0)),
      'endDate': Timestamp.fromDate(DateTime(2026, 5, 15, 22, 0)),
      'location': 'Lake Johnson Park',
      'eventType': 'social',
      'registrationDeadline': Timestamp.fromDate(DateTime(2026, 5, 14)),
      'maxParticipants': 75,
      'registeredUsers': [],
      'organizer': 'Social Committee',
      'isVirtual': false,
      'createdBy': 'system',
      'createdAt': Timestamp.now(),
    },
    {
      'title': 'Food Bank Volunteering',
      'description': 'Help sort donations at the local food bank – service hours available.',
      'date': Timestamp.fromDate(DateTime(2026, 4, 5, 10, 0)),
      'endDate': Timestamp.fromDate(DateTime(2026, 4, 5, 13, 0)),
      'location': 'Food Bank of Central NC',
      'eventType': 'service',
      'registrationDeadline': Timestamp.fromDate(DateTime(2026, 4, 3)),
      'maxParticipants': 20,
      'registeredUsers': [],
      'organizer': 'Community Service VP',
      'isVirtual': false,
      'createdBy': 'system',
      'createdAt': Timestamp.now(),
    },
    {
      'title': 'Car Wash Fundraiser',
      'description': 'Help raise money for chapter – \$10 per car.',
      'date': Timestamp.fromDate(DateTime(2026, 4, 19, 9, 0)),
      'endDate': Timestamp.fromDate(DateTime(2026, 4, 19, 15, 0)),
      'location': 'School Parking Lot',
      'eventType': 'fundraiser',
      'registrationDeadline': Timestamp.fromDate(DateTime(2026, 4, 18)),
      'maxParticipants': 15,
      'registeredUsers': [],
      'organizer': 'Fundraising Chair',
      'isVirtual': false,
      'createdBy': 'system',
      'createdAt': Timestamp.now(),
    },
  ];

  for (var event in events) {
    await firestore.collection('events').add(event);
  }
  print('All sample events seeded!');
}