// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAi73KFvaKJrnhNJRaAaT0tJiuymk8xdMA',
    appId: '1:108027945116:web:ce2bef6c195c192d170d59',
    messagingSenderId: '108027945116',
    projectId: 'fbla-mobile-application-327fc',
    authDomain: 'fbla-mobile-application-327fc.firebaseapp.com',
    storageBucket: 'fbla-mobile-application-327fc.firebasestorage.app',
    measurementId: 'G-2BR0DK46SE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLBYucW1gBGhAdCvA35HX8T2fGU2JUDKQ',
    appId: '1:108027945116:android:5de9ec113a7a0c1c170d59',
    messagingSenderId: '108027945116',
    projectId: 'fbla-mobile-application-327fc',
    storageBucket: 'fbla-mobile-application-327fc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAk0CGU4hqWXmoEO-QTwGXHkl8WZwNkdjc',
    appId: '1:108027945116:ios:f8ace576f152313d170d59',
    messagingSenderId: '108027945116',
    projectId: 'fbla-mobile-application-327fc',
    storageBucket: 'fbla-mobile-application-327fc.firebasestorage.app',
    iosBundleId: 'com.test.yourapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAk0CGU4hqWXmoEO-QTwGXHkl8WZwNkdjc',
    appId: '1:108027945116:ios:29e82e0e90458b2a170d59',
    messagingSenderId: '108027945116',
    projectId: 'fbla-mobile-application-327fc',
    storageBucket: 'fbla-mobile-application-327fc.firebasestorage.app',
    iosBundleId: 'com.example.assets',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAi73KFvaKJrnhNJRaAaT0tJiuymk8xdMA',
    appId: '1:108027945116:web:da8499486721b406170d59',
    messagingSenderId: '108027945116',
    projectId: 'fbla-mobile-application-327fc',
    authDomain: 'fbla-mobile-application-327fc.firebaseapp.com',
    storageBucket: 'fbla-mobile-application-327fc.firebasestorage.app',
    measurementId: 'G-T6M9Q28RSL',
  );

}